{
 "title": "Sales Report",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Total Sales",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(fact_sum_total_purchase) AS \"Total Sales\" FROM purchase_report \nWHERE purchase_time BETWEEN $__timeFrom() AND $__timeTo() "
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(fact_count_transactions) AS \"Transactions\" FROM purchase_report \nWHERE purchase_time BETWEEN $__timeFrom() AND $__timeTo() "
    }
   ]
  },
  {
   "title": "Units Sold",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(fact_sum_quantity) AS \"Transactions\" FROM purchase_report \nWHERE purchase_time BETWEEN $__timeFrom() AND $__timeTo() "
    }
   ]
  },
  {
   "title": "Sales per State",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), dim_state FROM purchase_report         \nWHERE purchase_time BETWEEN $__timeFrom() AND $__timeTo()  \nGROUP BY dim_state LIMIT 50 "
    }
   ]
  },
  {
   "title": "Category / State",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT dim_category, dim_state, SUM(fact_sum_total_purchase) AS \"Sales\" FROM purchase_report \nWHERE purchase_time BETWEEN $__timeFrom() AND $__timeTo() \nGROUP BY dim_category, dim_state ORDER BY dim_category "
    }
   ]
  },
  {
   "title": "Sales over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT SUM(fact_sum_supplement_price)  AS \"Supplements\", SUM(fact_sum_total_purchase) AS \"Total Sales\", purchase_time FROM purchase_report \nWHERE purchase_time BETWEEN $__timeFrom() AND $__timeTo() \nGROUP BY purchase_time"
    }
   ]
  }
 ]
}